document.addEventListener("DOMContentLoaded", async () => {
  // Elementos da interface
  const authCard = document.getElementById("authCard");
  const appSection = document.getElementById("app");
  const userEmail = document.getElementById("userEmail");
  const discContainer = document.getElementById("discContainer") || document.getElementById("discContainer");
  const discContainer = document.getElementById("discContainer") || document.getElementById("discContainer");
  const discContainer = document.getElementById("discContainer");
  const overallBar = document.getElementById("overallBar");
  const overallPct = document.getElementById("overallPct");
  const authErr = document.getElementById("authErr");
  const btnLogin = document.getElementById("btnLogin");
  const btnSignup = document.getElementById("btnSignup");
  const btnLogout = document.getElementById("btnLogout");

  // Estado do usuário
  let currentUser = null;

  // Inicializar cliente Supabase
  const sb = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);

  // ================== BANCO / CHECK TABLE ==================
  // Verificar se a tabela `estudo` existe tentando query simples
  let tabelaExiste = true;
  try {
    await sb.from("estudo").select("id").limit(1);
  } catch (e) {
    console.warn("Tabela `estudo` provavelmente não existe. Tentando criar…");
    tabelaExiste = false;
  }

  // Se não existir, criar via RPC SQL
  if (!tabelaExiste) {
    try {
      const { error } = await sb.rpc("exec_sql", {
        sql: `
        CREATE TABLE IF NOT EXISTS estudo (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id UUID NOT NULL,
          topico TEXT NOT NULL,
          estudado BOOLEAN DEFAULT FALSE,
          UNIQUE(user_id, topico)
        );
        `
      });
      if (error) console.error("Falha ao criar tabela:", error);
      else console.log("Tabela `estudo` criada ou já existente.");
    } catch (err) {
      console.error("Erro ao criar tabela `estudo` via RPC:", err);
    }
  }

  // Ativar RLS + policies (melhor esforço, se já não estiver)
  try {
    await sb.rpc("exec_sql", {
      sql: `
      ALTER TABLE estudo ENABLE ROW LEVEL SECURITY;
      CREATE POLICY IF NOT EXISTS "select_dono" ON estudo FOR SELECT USING (auth.uid() = user_id);
      CREATE POLICY IF NOT EXISTS "update_dono" ON estudo FOR UPDATE USING (auth.uid() = user_id);
      `
    });
  } catch (e) {
    console.warn("Aviso ao aplicar RLS/policies (pode ignorar se já existem):", e.message);
  }

  // ================== CARREGAR EDITAL JSON ==================
  async function carregarEdital() {
    try {
      const r = await fetch("edital_auditor.json");
      return await r.json();
    } catch (e) {
      console.error("Erro ao carregar edital JSON:", e);
      return null;
    }
  }

  const edital = await carregarEdital();
  if (!edital) {
    discContainer.textContent = "Erro: não foi possível carregar o edital JSON.";
    return;
  }

  // ================== RENDERIZAR DISCIPLINAS/TÓPICOS ==================
  async function renderUI(user) {
    discContainer.innerHTML = "";

    let totalTopicos = 0;
    let totalEstudados = 0;

    for (const d of edital.disciplinas) {
      let bloco = `<div class="card section"><div class="disc-head"><strong>${d.nome}</strong></div>`;

      // Sub-seções
      if (d.subsecoes) {
        for (const s of d.subsecoes) {
          bloco += `<div class="group"><h3>${s.nome}</h3><ul class="topics">`;
          for (const t of s.topicos) {
            totalTopicos++;
            const { data } = await sb
              .from("estudo")
              .select("estudado")
              .eq("user_id", user.id)
              .eq("topico", t)
              .single();

            const estudado = data?.estudado === true;
            if (estudado) totalEstudados++;

            bloco += `
              <li class="topic ${estudado ? "done" : ""}" data-topico="${t}">
                <span class="check">☑</span>
                <span class="text">${t}</span>
              </li>`;
          }
          bloco += `</ul></div>`;
        }
      }

      // Tópicos diretos
      else if (d.topicos) {
        bloco += `<ul class="topics">`;
        for (const t of d.topicos) {
          totalTopicos++;
          const { data } = await sb
            .from("estudo")
            .select("estudado")
            .eq("user_id", user.id)
            .eq("topico", t)
            .single();

          const estudado = data?.estudado === true;
          if (estudado) totalEstudados++;

          bloco += `
            <li class="topic ${estudado ? "done" : ""}" data-topico="${t}">
              <span class="check">☑</span>
              <span class="text">${t}</span>
            </li>`;
        }
        bloco += `</ul>`;
      }

      bloco += `</div></div>`;
      discContainer.innerHTML += bloco;
    }

    const pct = totalTopicos ? Math.round((totalEstudados / totalTopicos) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  // ================== LOGIN / SIGNUP / LOGOUT ==================
  btnLogin.onclick = async () => {
    const { data, error } = await sb.auth.signInWithPassword({
      email: email.value.trim(),
      password: password.value.trim()
    });

    if (error) {
      authErr.textContent = "Falha no login.";
      authErr.classList.remove("hide");
      return;
    }

    currentUser = data.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");

    await renderUI(currentUser);
  };

  btnSignup.onclick = async () => {
    const { error } = await sb.auth.signUp({
      email: email.value.trim(),
      password: password.value.trim()
    });
    if (error) {
      authErr.textContent = "Erro ao criar conta.";
      authErr.classList.remove("hide");
    }
  };

  // Marcar estudo ao clicar
  document.addEventListener("click", async (e) => {
    const item = e.target.closest(".topic");
    if (!item || !currentUser) return;

    const topico = item.getAttribute("data-topico");
    const novoEstado = !item.classList.contains("done");

    try {
      const { error } = await sb
        .from("estudo")
        .upsert({ user_id: currentUser.id, topico, estudado: novoEstado });

      if (!error) {
        item.classList.toggle("done", novoEstado);
        atualizarProgresso();
      }
    } catch (err) {
      console.error("Erro ao salvar tópico estudado:", err);
    }
  });

  function atualizarProgresso() {
    const feitos = document.querySelectorAll(".topic.done").length;
    const total = document.querySelectorAll(".topic").length;
    const pct = total ? Math.round((feitos / total) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  btnLogout.onclick = () => location.reload();

  // Auto-login se já existir sessão ativa
  const sess = await sb.auth.getSession();
  if (sess.data.session?.user) {
    currentUser = sess.data.session.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");
    await renderUI(currentUser);
  }
});
