document.addEventListener("DOMContentLoaded", async () => {
  const sb = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
  const discContainer = document.getElementById("discContainer");
  const overallBar = document.getElementById("overallBar");
  const overallPct = document.getElementById("overallPct");
  const authCard = document.getElementById("authCard");
  const appSection = document.getElementById("app");
  const userEmail = document.getElementById("userEmail");
  const btnLogout = document.getElementById("btnLogout");
  const authErr = document.getElementById("authErr");

  let currentUser = null;

  // Carregar JSON do edital (arquivo local)
  async function carregarEdital() {
    try {
      const r = await fetch("edital_auditor.json");
      return await r.json();
    } catch {
      return null;
    }
  }

  const edital = await carregarEdital();
  if (!edital) {
    discContainer.textContent = "Não foi possível carregar o edital.";
    return;
  }

  // Renderizar UI completa com todos os tópicos
  async function renderUI(user) {
    discContainer.innerHTML = "";
    const disciplinas = edital.disciplinas;
    let totalTopicos = 0;
    let totalEstudados = 0;

    for (const d of disciplinas) {
      let bloco = `<div class="card section"><div class="disc-head"><strong>${d.nome}</strong></div>`;

      // Caso tenha subseções
      if (d.subsecoes) {
        for (const s of d.subsecoes) {
          bloco += `<div class="group"><h3>${s.nome}</h3><ul class="topics">`;
          for (const t of s.topicos) {
            totalTopicos++;
            const { data } = await sb
              .from("estudo")
              .select("estudado")
              .eq("user_id", user.id)
              .eq("topico", t)
              .single();

            const estudado = data?.estudado === true;
            if (estudado) totalEstudados++;

            bloco += `
              <li class="topic ${estudado ? "done" : ""}" data-topico="${t}">
                <span class="check">☑</span>
                <span class="text">${t}</span>
              </li>`;
          }
          bloco += `</ul></div>`;
        }
      }

      // Caso tenha tópicos diretos
      else if (d.topicos) {
        bloco += `<ul class="topics">`;
        for (const t of d.topicos) {
          totalTopicos++;
          const { data } = await sb
            .from("estudo")
            .select("estudado")
            .eq("user_id", user.id)
            .eq("topico", t)
            .single();

          const estudado = data?.estudado === true;
          if (estudado) totalEstudados++;

          bloco += `
            <li class="topic ${estudado ? "done" : ""}" data-topico="${t}">
              <span class="check">☑</span>
              <span class="text">${t}</span>
            </li>`;
        }
        bloco += `</ul>`;
      }

      bloco += `</div>`;
      discContainer.innerHTML += bloco;
    }

    // Atualizar progresso geral
    const pct = totalTopicos ? Math.round((totalEstudados / totalTopicos) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  // Criar tabela de persistência no Supabase se não existir
  await sb.from("estudo").select("topico").limit(1).catch(async () => {
    await sb.rpc("exec_sql", {
      sql: `CREATE TABLE IF NOT EXISTS estudo (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL,
        topico TEXT NOT NULL,
        estudado BOOLEAN DEFAULT FALSE,
        UNIQUE(user_id, topico)
      );`
    });
  });

  // Login
  document.getElementById("btnLogin").onclick = async () => {
    const { data, error } = await sb.auth.signInWithPassword({
      email: email.value.trim(),
      password: password.value.trim()
    });

    if (error) {
      authErr.textContent = "Falha no login.";
      authErr.classList.remove("hide");
      return;
    }

    currentUser = data.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");

    await renderUI(currentUser);
  };

  // Clique para marcar estudo e salvar
  document.addEventListener("click", async (e) => {
    const item = e.target.closest(".topic");
    if (!item || !currentUser) return;

    const topico = item.getAttribute("data-topico");
    const novoEstado = !item.classList.contains("done");

    const { error } = await sb
      .from("estudo")
      .upsert({ user_id: currentUser.id, topico, estudado: novoEstado });

    if (!error) {
      item.classList.toggle("done", novoEstado);
      atualizarProgresso();
    }
  });

  function atualizarProgresso() {
    const feitos = document.querySelectorAll(".topic.done").length;
    const total = document.querySelectorAll(".topic").length;
    const pct = total ? Math.round((feitos / total) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  // Logout
  btnLogout.onclick = () => location.reload();

  // Auto-login se já existir sessão ativa
  const sess = await sb.auth.getSession();
  if (sess.data.session?.user) {
    currentUser = sess.data.session.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");
    await renderUI(currentUser);
  }
});
