document.addEventListener("DOMContentLoaded", async () => {
  // Inicializar cliente Supabase
  const sb = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);

  // Elementos da UI
  const authCard = document.getElementById("authCard");
  const appSection = document.getElementById("app");
  const userEmail = document.getElementById("userEmail");
  const discContainer = document.getElementById("discContainer");
  const overallBar = document.getElementById("overallBar");
  const overallPct = document.getElementById("overallPct");
  const authErr = document.getElementById("authErr");
  const email = document.getElementById("email");
  const password = document.getElementById("password");
  const btnLogin = document.getElementById("btnLogin");
  const btnLogout = document.getElementById("btnLogout");
  const btnSignup = document.getElementById("btnSignup");

  let currentUser = null;

  // =============== VERIFICAR / CRIAR TABELA ===============
  // Verifica se a tabela `estudo` existe
  let tabelaExiste = true;
  try {
    await sb.from("estudo").select("id").limit(1);
  } catch (e) {
    tabelaExiste = false;
  }

  // Se não existir, tenta criar com SQL via RPC genérico
  if (!tabelaExiste) {
    try {
      await sb.rpc("exec_sql", {
        sql: `
        CREATE TABLE IF NOT EXISTS estudo (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id UUID NOT NULL,
          topico TEXT NOT NULL,
          estudado BOOLEAN DEFAULT FALSE,
          UNIQUE(user_id, topico)
        );
        ALTER TABLE estudo ENABLE ROW LEVEL SECURITY;
        CREATE POLICY IF NOT EXISTS "select_dono" ON estudo FOR SELECT USING (auth.uid() = user_id);
        CREATE POLICY IF NOT EXISTS "update_dono" ON estudo FOR UPDATE USING (auth.uid() = user_id);
        `
      });
    } catch (err) {
      console.warn("Aviso ao criar tabela (ignore se já existir no projeto):", err.message);
    }
  }

  // =============== CARREGAR EDITAL JSON ===============
  async function carregarEdital() {
    try {
      const r = await fetch("edital_auditor.json");
      return await r.json();
    } catch {
      return null;
    }
  }

  const edital = await carregarEdital();
  if (!edital) {
    discContainer.textContent = "Erro ao carregar edital.";
    return;
  }

  // =============== RENDERIZAR DISCIPLINAS E TÓPICOS ===============
  async function renderUI(user) {
    discContainer.innerHTML = "";

    let totalTopicos = 0;
    let totalEstudados = 0;

    for (const d of edital.disciplinas) {
      let bloco = `<div class="card section"><div class="disc-head"><strong>${d.nome}</strong></div>`;

      if (d.subsecoes) {
        for (const s of d.subsecoes) {
          bloco += `<div class="group"><h3>${s.nome}</h3><ul class="topics">`;
          for (const t of s.topicos) {
            totalTopicos++;
            const { data } = await sb
              .from("estudo")
              .select("estudado")
              .eq("user_id", user.id)
              .eq("topico", t)
              .single();

            const estudado = data?.estudado === true;
            if (estudado) totalEstudados++;

            bloco += `
              <li class="topic ${estudado ? "done" : ""}" data-id="${t}">
                <span class="text">${t}</span>
              </li>`;
          }
          bloco += `</ul></div>`;
        }
      } else if (d.topicos) {
        bloco += `<ul class="topics">`;
        for (const t of d.topicos) {
          totalTopicos++;
          const { data } = await sb
            .from("estudo")
            .select("estudado")
            .eq("user_id", user.id)
            .eq("topico", t)
            .single();

          const estudado = data?.estudado === true;
          if (estudado) totalEstudados++;

          bloco += `
            <li class="topic ${estudado ? "done" : ""}" data-id="${t}">
              <span class="text">${t}</span>
            </li>`;
        }
        bloco += `</ul>`;
      }

      bloco += `</div></div>`;
      discContainer.innerHTML += bloco;
    }

    const pct = totalTopicos ? Math.round((totalEstudados / totalTopicos) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  // =============== LOGIN ===============
  btnLogin.onclick = async () => {
    const { data, error } = await sb.auth.signInWithPassword({
      email: email.value.trim(),
      password: password.value.trim()
    });

    if (error) {
      authErr.textContent = "Login rejeitado pelo servidor.";
      authErr.classList.remove("hide");
      return;
    }

    currentUser = data.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");

    await renderUI(currentUser);
  };

  // =============== SIGNUP ===============
  btnSignup.onclick = async () => {
    const { error } = await sb.auth.signUp({
      email: email.value.trim(),
      password: password.value.trim()
    });
    if (error) {
      authErr.textContent = "Falha ao criar conta.";
      authErr.classList.remove("hide");
    } else {
      authErr.textContent = "Conta criada. Confirme o e-mail antes de entrar.";
      authErr.classList.remove("hide");
    }
  };

  // =============== MARCAR ESTUDO AO CLICAR ===============
  document.addEventListener("click", async (e) => {
    const item = e.target.closest(".topic");
    if (!item || !currentUser) return;

    const topico = item.querySelector(".text").textContent;
    const novoEstado = !item.classList.contains("done");

    try {
      await sb.from("estudo").upsert({
        user_id: currentUser.id,
        topico: topico,
        estudado: novoEstado
      });
      item.classList.toggle("done", novoEstado);
      atualizarProgresso();
    } catch (err) {
      console.error("Erro ao salvar estudo:", err);
    }
  });

  function atualizarProgresso() {
    const feitos = document.querySelectorAll(".topic.done").length;
    const total = document.querySelectorAll(".topic").length;
    const pct = total ? Math.round((feitos / total) * 100) : 0;
    overallBar.style.width = pct + "%";
    overallPct.textContent = pct;
  }

  // Logout apenas recarrega a página (não edita calendário)
  btnLogout.onclick = () => location.reload();

  // Auto-login se a sessão já estiver ativa
  const sess = await sb.auth.getSession();
  if (sess.data.session?.user) {
    currentUser = sess.data.session.user;
    userEmail.textContent = currentUser.email;
    authCard.classList.add("hide");
    appSection.classList.remove("hide");
    btnLogout.classList.remove("hide");
    await renderUI(currentUser);
  }
});
